### ISSUE TITLE
Uncaught TypeError: history.listen is not a function

### ISSUE THREAD

**Issue by jackyon** [blackbing/use-scroll-behavior#2]
Hi, 
after i installed and follow with the usage
the error came out: Uncaught TypeError: history.listen is not a function. 

here is my codes:

```
import React from 'react';
import { render } from 'react-dom';
import { Provider } from 'react-redux';
import { Router } from 'react-router';
import useScroll from 'use-scroll-behavior';
import browserHistory from 'history/lib/createBrowserHistory';
import { syncHistoryWithStore } from 'react-router-redux';
import configureStore from './store/configureStore';
import routes from './routes';

const store = configureStore();
const history = useScroll(browserHistory);

syncHistoryWithStore( history, store );

render(
    <Provider store={store}>
        <Router history={history} routes={routes} />
    </Provider>,
    document.getElementById( 'app' )
);

```

plz advise if i am doing something wrong, thx!

**Comment by blackbing** [comment]
@jackyon : you should use 

``` js
import { browserHistory } from 'react-router';
```

**Comment by jackyon** [comment]
@blackbing  maybe is the problem from the version of react-router, i am still using version 1.0.0, I will try to upgrade the version and see if this issue still exist.

thx!

**Comment by blackbing** [comment]
I see, can you try this?

``` js
import browserHistory from 'history/lib/createBrowserHistory';
//create history by createBrowserHistory
const history = useScroll(browserHistory());
```

**Comment by jackyon** [comment]
hi, seems still not wokring.

error: Uncaught TypeError: Cannot convert undefined or null to object

```
import React from 'react';
import { render } from 'react-dom';
import { Provider } from 'react-redux';
import { Router } from 'react-router';
import useScroll from 'use-scroll-behavior';
import browserHistory from 'history/lib/createBrowserHistory';
import { syncHistoryWithStore } from 'react-router-redux';
import configureStore from './store/configureStore';
import routes from './routes';

const store = configureStore();
const history = useScroll(browserHistory());

syncHistoryWithStore( history, store );

render(
    <Provider store={store}>
        <Router history={history} routes={routes} />
    </Provider>,
    document.getElementById( 'app' )
);

```

plz advise, thx

**Comment by blackbing** [comment]
I got the problem, I will try to add `createBrowserHistory` lib support in next version.

**Comment by jackyon** [comment]
thx, can't wait for the next version.

**Comment by blackbing** [comment]
@jackyon I released 0.0.6 version. please help to check it is fixed.

**Comment by jackyon** [comment]
@blackbing 
looks like the scroll position is wrong in the next page. it should be scroll to top at next page.

I have recorded one video for explaining this issue, see the below youtube link plz:
https://youtu.be/xUU05hvL1Uc

thx.

**Comment by blackbing** [comment]
Do you mean the X position is not correct? For currently, I use y position only. I will add x position in the future.

**Comment by jackyon** [comment]
no, I mean the y position is not correct, you can see from the video link, in the home page i scroll to the bottom, and then you can realize the position is not to the top after I click the about link

**Comment by jackyon** [comment]
原來妳是臺灣的，那我就打中文吧，這樣解釋可能清楚點， 我的意思是：

在 home 頁面的時候，我滾動到頁面最底下，然後我點擊了導航欄的 about 鏈接，跳到新頁面後，頁面位置是錯誤的，頁面的位置應該是在頁面最頂上，這樣才是正確的。

請問看得懂我描述了嗎？

**Comment by blackbing** [comment]
move issue discussion to #3
