### ISSUE TITLE
scroll position is not correct 

### ISSUE THREAD

**Issue by blackbing** [blackbing/use-scroll-behavior#3]
based on https://github.com/blackbing/use-scroll-behavior/issues/2#issuecomment-203991024 mentioned. ref video: https://youtu.be/xUU05hvL1Uc

> 在 home 頁面的時候，我滾動到頁面最底下，然後我點擊了導航欄的 about 鏈接，跳到新頁面後，頁面位置是錯誤的，頁面的位置應該是在頁面最頂上，這樣才是正確的。

**Comment by ChrisCinelli** [comment]
This may be because you use `lodash.throttle'` instead of `lodash.debounce`:
https://css-tricks.com/debouncing-throttling-explained-examples/

With throttle if you have a burst of events, it may skip the actual final position.

**Comment by blackbing** [comment]
@ChrisCinelli thanks for your advise and I've released [[0.1.5]](https://github.com/blackbing/use-scroll-behavior/tree/0.1.5)
